name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        config:
          # - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          - {
              name: "Ubuntu",
              os: ubuntu-latest,
              cc: "clang",
              cxx: "clang++",
              generator: "Ninja",
            }
          - {
              name: "macOS",
              os: macos-latest,
              cc: "clang",
              cxx: "clang++",
              generator: "Ninja",
            }
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }}-${{ matrix.config.cc }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.config.os, 'ubuntu-')
        run: |
          sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends \
          gcc-multilib \
          libasound2-dev \
          libpulse-dev \
          libglfw3 \
          libglfw3-dev \
          libx11-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libxext-dev \
          libxfixes-dev
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: bin/rake test
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
          CMAKE_C_COMPILER: ${{ matrix.config.cc }}
          CMAKE_CXX_COMPILER: ${{ matrix.config.cxx }}
          CMAKE_GENERATOR: ${{ matrix.config.generator }}
          CMAKE_MAKE_PROGRAM: ninja
