name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        config:
          # - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          - {
              name: "Ubuntu gcc",
              os: ubuntu-latest,
              cc: "gcc",
              cxx: "g++",
              generator: "Ninja",
            }
          - {
              name: "MacOS clang",
              os: macos-latest,
              cc: "clang",
              cxx: "clang++",
              generator: "Ninja",
            }
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update && sudo apt-get install -y \
          libasound2-dev \
          libpulse-dev \
          libaudio-dev \
          libjack-dev \
          libsndio-dev \
          libusb-1.0-0-dev \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxfixes-dev \
          libxi-dev \
          libxss-dev \
          libwayland-dev \
          libxkbcommon-dev \
          libdrm-dev \
          libgbm-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          libegl1-mesa-dev \
          libdbus-1-dev \
          libibus-1.0-dev \
          libudev-dev \
          fcitx-libs-dev
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Run tests
        run: rake test
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
          CMAKE_C_COMPILER: ${{ matrix.config.cc }}
          CMAKE_CXX_COMPILER: ${{ matrix.config.cxx }}
          CMAKE_GENERATOR: ${{ matrix.config.generator }}
          CMAKE_MAKE_PROGRAM: ninja
